# Keep everything on one line
add_newline = false

format = "$directory$git_branch$character"

# Directory formatting
[directory]
style = "bold #d8a7d1"
truncation_length = 3
truncation_symbol = "/"
read_only = "ğŸ”’"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold #b6e3b0"
format = "on [$symbol$branch]($style)"

[git_status]
style = "bright-yellow"
format = '[ ($all_status$ahead_behind)]($style)'
staged = '[â—](bright-green)'
modified = '[âœ](bright-yellow)'
untracked = '[?](bright-cyan)'
deleted = '[âœ˜](bright-red)'
stashed = '[ğŸ’¾](bright-blue)'
conflicted = '[â€¼](bright-magenta)'
# only_nonzero_diffs = true

[character]
success_symbol = '[ â¨à¹‘â€¢Ì€ã…‚â€¢Ìâ©à¸‡âœ§âœ](#a3d9a5)'
error_symbol = "[â¨â—¡_â—¡â©á•¤ âœ–](#e8a4a4)"

[battery]
disabled = true
